// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Assert from "assert";
import WebTreeSitter from "web-tree-sitter";
import * as WebTreeSitter$1 from "web-tree-sitter";

async function loadFile(param) {
  return Path.resolve("artifact", "tree-sitter-rescript.wasm");
}

((async function (param) {
        await WebTreeSitter$1.default.init(undefined);
        var parser = new WebTreeSitter();
        var wasm_file = await loadFile(undefined);
        var rescript = await WebTreeSitter$1.default.Language.load(wasm_file);
        parser.setLanguage(rescript);
        var tree = parser.parse("let a = 1\n", undefined, undefined);
        Assert.equal(tree.rootNode.toString(), "(source_file (let_binding (value_identifier) (number)))");
      })(undefined));

export {
  loadFile ,
}
/*  Not a pure module */
