// Generated by ReScript, PLEASE EDIT WITH CARE

import WebTreeSitter from "web-tree-sitter";
import * as WebTreeSitter$1 from "web-tree-sitter";

((async function (param) {
        await WebTreeSitter$1.init(undefined);
        var parser = new WebTreeSitter();
        var rescript = WebTreeSitter$1.Language.load("file");
        rescript.fieldIdForName("variable");
        parser.setLanguage(rescript);
        var tree = parser.parse("let a = 1\n", undefined, undefined);
        console.log(tree.rootNode.hasError());
        console.log(tree.rootNode.toString());
      })(undefined));

export {
  
}
/*  Not a pure module */
