// Generated by ReScript, PLEASE EDIT WITH CARE


var Language = {};

var SyntaxNode = {};

var TreeCursor = {};

var Tree = {};

var Query = {};

var Parser = {
  Language: Language,
  SyntaxNode: SyntaxNode,
  TreeCursor: TreeCursor,
  Tree: Tree,
  Query: Query
};

export {
  Parser ,
}
/* No side effect */
